# Generated by Django 4.2.4 on 2023-09-12 07:25

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('seeker_foods', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='restaurants',
            old_name='city',
            new_name='location',
        ),
    ]
