# Generated by Django 4.2.4 on 2023-09-16 17:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('seeker_foods', '0002_rename_city_restaurants_location'),
    ]

    operations = [
        migrations.RenameField(
            model_name='restaurants',
            old_name='location',
            new_name='city',
        ),
        migrations.RemoveField(
            model_name='restaurants',
            name='rating',
        ),
        migrations.AddField(
            model_name='restaurants',
            name='country',
            field=models.CharField(default='Sri Lanka', max_length=30),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='restaurants',
            name='email',
            field=models.EmailField(blank=True, max_length=254, null=True),
        ),
        migrations.AddField(
            model_name='restaurants',
            name='website',
            field=models.URLField(blank=True, null=True),
        ),
    ]
